data:
  path_to_trainfiles: "/data/ravinascos/Lund_Plane_2024_graphs/New_Samples/Pythia_TRAIN_05QCD_25Z_25W/*.root" #TRAIN_DUMMY_fewEvents # TRAIN_DUMMY_01QCD_05Z
  #path_to_save: "/home/ravinascos/LundNet/Jad_git/lundtoptagger/Models/"
  path_to_save: "/data/ravinascos/LundNet/2024_graphs/"
  # model_name: "LundNet_R22_No_ln_kT_Cut_LRJ_NewData_Primary"
  model_name: "LundNet_R22_ExtraNode_ln_kT_Cut_{ln_kT_cut}_LRJ_NewData_Primary"
  ln_kT_cut: null # null, -0.5, 0.0, 0.5, 1.0, 2.0, 2.8

architecture:
  batch_size: 1200
  test_size: 0.2
  n_epochs: 30
  learning_rate: 0.0005
  choose_model: LundNet ## LundNet, GATNet, GINNet, EdgeGinNet, PNANet
  save_every_epoch: True

retrain:
  flag: False
  path_to_ckpt: "/sps/atlas/k/khandoga/TrainGNN/Models/LundNet_ufob_e012_0.12481.pt"
