signal: W  # W or top, flag to choose one of the configurations below

top:
  # weights_file: "/data/jmsardain/LJPTagger/FullSplittings/SplitForTopTagger/flat_weights.root"
  weights_file: "/data/jmsardain/LJPTagger/FullSplittings/SplitForTopTagger/5_Signal_and_BKG_cutTruth350/flat_weights.root"
  pt_hist_file_bkg: "/data/bcifuentes/histograms/qcd.root"
  pt_hist_file_signal: "/data/bcifuentes/histograms/top.root"
  signal_jet_truth_label: 1
  skip_dsids:
  - 364700  # don't lose time with jets that don't pass pt cut
  - 364701  # don't lose time with jets that don't pass pt cut
  - 364702  # don't lose time with jets that don't pass pt cut
  - 801859  # don't keep W jets

W:
  weights_file: "/eos/home-t/tmlinare/Lund/Lund_tagging/ljptagger/flat_weights.root"
  pt_hist_file_bkg: "/eos/home-t/tmlinare/Lund/Lund_tagging/lundtoptagger/qcd.root"
  pt_hist_file_signal: "/eos/home-t/tmlinare/Lund/Lund_tagging/lundtoptagger/top.root"
  signal_jet_truth_label: 2
  skip_dsids:
  - 364700  # don't lose time with jets that don't pass pt cut
  - 364701  # don't lose time with jets that don't pass pt cut
  - 364702  # don't lose time with jets that don't pass pt cut
  - 801661  # don't keep top jets